# Gerado automaticamente para o Kitty
background #08121D
foreground #cfdae2
selection_background #2d353e
selection_foreground #cfdae2

color0  #08121D
color1  #0A2F53
color2  #286392
color3  #124C6D
color4  #57A4C2
color5  #353236
color6  #57A4C2
color7  #cfdae2

color8  #5e646c
color9  #536d86
color10 #6891b2
color11 #124C6D
color12 #89bfd4
color13 #353236
color14 #89bfd4
color15 #ffffff
