# Gerado automaticamente para o Kitty
background #302F2D
foreground #cfdae2
selection_background #4f4e4c
selection_foreground #cfdae2

color0  #302F2D
color1  #47454F
color2  #59648B
color3  #4F372C
color4  #634732
color5  #9E5B47
color6  #634732
color7  #cfdae2

color8  #787776
color9  #7e7c83
color10 #8a92ad
color11 #4F372C
color12 #917e6f
color13 #9E5B47
color14 #917e6f
color15 #ffffff
