# Gerado automaticamente para hyprlock
$bg       = rgb(6299B4)
$surface  = rgb(79a8bf)
$fg       = rgb(cfdae2)
$muted    = rgb(98bcce)

$accent   = rgb(DBE8EE)
$red      = rgb(6DA6E5)
$yellow   = rgb(7A7880)
$green    = rgb(A2D2EB)
$blue     = rgb(A4B3C4)

# cores de texto/UI
$time_hour   = rgb(DBE8EE)
$time_minute = rgb(A4B3C4)
$date_color  = rgb(cfdae2)
$user_color  = rgb(cfdae2)
$outer_color = rgb(DBE8EE)
$inner_color = rgb(79a8bf)
$font_color  = rgb(cfdae2)
$song_color  = rgb(DBE8EE)
