# Gerado automaticamente para hyprlock
$bg       = rgb(301F11)
$surface  = rgb(4f4034)
$fg       = rgb(cfdae2)
$muted    = rgb(786d64)

$accent   = rgb(F98E62)
$red      = rgb(5B3228)
$yellow   = rgb(704946)
$green    = rgb(704733)
$blue     = rgb(B75C4A)

# cores de texto/UI
$time_hour   = rgb(F98E62)
$time_minute = rgb(B75C4A)
$date_color  = rgb(cfdae2)
$user_color  = rgb(cfdae2)
$outer_color = rgb(F98E62)
$inner_color = rgb(4f4034)
$font_color  = rgb(cfdae2)
$song_color  = rgb(F98E62)
