# Gerado automaticamente para hyprlock
$bg       = rgb(282828)
$surface  = rgb(484848)
$fg       = rgb(cfdae2)
$muted    = rgb(737373)

$accent   = rgb(353236)
$red      = rgb(4C3835)
$yellow   = rgb(56655F)
$green    = rgb(918579)
$blue     = rgb(93A696)

# cores de texto/UI
$time_hour   = rgb(353236)
$time_minute = rgb(93A696)
$date_color  = rgb(cfdae2)
$user_color  = rgb(cfdae2)
$outer_color = rgb(353236)
$inner_color = rgb(484848)
$font_color  = rgb(cfdae2)
$song_color  = rgb(353236)
